### ISSUE TITLE
wishlist: translatable headings in living wage table

### ISSUE THREAD

**Issue by polyester** [wikirate/transparency-tool#14]
the headings "Food", "Housing" etc in
https://github.com/wikirate/transparency-tool/blob/master/source/localizable/partials/shared/_living_wage_table.html.haml are not translatable.

**Comment by aileenrob** [comment]
Hi @polyester - this issue should be fixed now

**Comment by polyester** [comment]
It is not; if you put in translations in for instance de.yml, it starts looking (and fails to find) translated versions of the icons and the flip-card
See screenshot. We should probably take some time to properly test this on staging.

![Screenshot from 2020-06-24 14-03-09](https://user-images.githubusercontent.com/456196/85552766-a1a0c500-b623-11ea-838d-5a3f061f892d.png)

**Comment by aileenrob** [comment]
Thanks for the extra details Paul. I will link Ethan back to this!

**Comment by polyester** [comment]
See also https://github.com/wikirate/transparency-tool/issues/21

The translation machinery is a bit ruthless, it should be told to not translate some parts like images and icons. I'll see if I can dive into it a bit as well later.

**Comment by ethn** [comment]
I think this is fixed, no?

**Comment by polyester** [comment]
No; you have to actually put in a value in the translation key. It uses the key as heading, but also to look up the text of the flipcard and the icon. So if you put 
`education:` "Bildung"
into de.yml, it changes the heading in the table to "Bildung", but shows no icon, and when you flip it it says
translation missing: de.livingwage_table.minimum_wage.bildung

**Comment by ethn** [comment]
OK, I think the translation headers are fixed in master. (Not deployed; have to set up staging first).

I fixed some key images, eg on brand results, but let me know if you're still seeing any broken.

**Comment by polyester** [comment]
seems to work, except that the compare-table image for "health_care" is gone (also in English). The others work

**Comment by polyester** [comment]
ah, minor type in the scss. Healthcare for all!!
(the scss file had health-care instead of health_care)
https://github.com/wikirate/transparency-tool/pull/22
