### ISSUE TITLE
Colour tweak on MW/LW table

### ISSUE THREAD

**Issue by heatherknight08** [wikirate/transparency-tool#24]
Colour needs to be adjusted so that the MW column isn't invisible
<img width="531" alt="Screenshot 2020-06-25 at 09 33 44" src="https://user-images.githubusercontent.com/67009459/85685546-124ced80-b6c7-11ea-84f2-b1a467f177f8.png">

Should be:
<img width="405" alt="Screenshot 2020-06-25 at 09 35 42" src="https://user-images.githubusercontent.com/67009459/85685753-41fbf580-b6c7-11ea-82e1-ae1f97f34a9a.png">

Background colour should be #1D1D2F

**Comment by polyester** [comment]
@ethn I picked this up, fix is included in https://github.com/wikirate/transparency-tool/pull/28
