### ISSUE TITLE
hyperlink needed on Take Action page?

### ISSUE THREAD

**Issue by heatherknight08** [wikirate/transparency-tool#25]
@polyester
Just in case this isn't on your list already, we should probably include a hyperlink, list or button to the national websites here.  

<img width="594" alt="Screenshot 2020-06-25 at 09 37 54" src="https://user-images.githubusercontent.com/67009459/85686159-9f904200-b6c7-11ea-997e-9d46f20b5cfb.png">

**Comment by polyester** [comment]
Yes, on my list of todo's for today. We may want to directly list them here, with logo, or point to https://cleanclothes.org/about/the-european-coalition

**Comment by polyester** [comment]
Solved, waiting for Ethan to merge https://github.com/wikirate/transparency-tool/pull/28

**Comment by ethn** [comment]
merged. ok to close?

**Comment by polyester** [comment]
Yep, this one I can't close, but OK to close
